# Generated by Django 3.2.2 on 2021-05-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalenderEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateField(auto_now_add=True)),
                ('starting_at', models.DateTimeField()),
                ('ending_at', models.DateTimeField()),
                ('subject', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100, null=True)),
                ('link', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
