# Generated by Django 3.2.2 on 2021-05-07 19:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calenderevents',
            name='time',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='meetings',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calenderevents',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='ending_at',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='starting_at',
            field=models.TimeField(),
        ),
    ]
