# Generated by Django 3.2.2 on 2021-05-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_app', '0003_auto_20210508_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calenderevents',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
