# Generated by Django 3.2.2 on 2021-05-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_app', '0004_alter_calenderevents_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calenderevents',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='calenderevents',
            name='desc',
            field=models.CharField(default='', max_length=255),
        ),
    ]
