# Generated by Django 3.2.2 on 2021-05-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_app', '0005_auto_20210508_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='calenderevents',
            name='color',
            field=models.CharField(default='orange', max_length=10),
        ),
    ]
