# Generated by Django 3.2.2 on 2021-05-09 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom_app', '0006_calenderevents_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateField(auto_now_add=True)),
                ('date', models.DateField()),
                ('starting_at', models.TimeField()),
                ('ending_at', models.TimeField()),
                ('subject', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('creater', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creater', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='CalenderEvents',
            new_name='CalenderEvent',
        ),
        migrations.DeleteModel(
            name='Meetings',
        ),
    ]
